# Generated by Django 5.2.6 on 2025-10-16 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edges',
            fields=[
                ('edge_key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('relation', models.CharField(max_length=100)),
                ('escalator', models.IntegerField(default=0)),
                ('out_of_order', models.IntegerField(default=0)),
                ('is_escalator', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'edges',
            },
        ),
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('node_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('line', models.CharField(max_length=50)),
                ('node_name', models.CharField(max_length=100)),
                ('floor', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=50)),
                ('station', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'nodes',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('profile_image', models.TextField(blank=True, null=True)),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('google_mail', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Lines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=50)),
                ('station', models.CharField(max_length=100)),
                ('order_in_line', models.IntegerField()),
            ],
            options={
                'db_table': 'lines',
                'unique_together': {('line', 'order_in_line')},
            },
        ),
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=100)),
                ('line', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'stations',
                'unique_together': {('station', 'line')},
            },
        ),
    ]
