# Generated by Django 5.2.6 on 2025-11-10 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'line',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('floor', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'node',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('profile_image', models.TextField(blank=True, null=True)),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('google_mail', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Lines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=50)),
                ('station', models.CharField(max_length=100)),
                ('order_in_line', models.IntegerField()),
            ],
            options={
                'db_table': 'lines',
                'unique_together': {('line', 'order_in_line')},
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('escalator', models.BooleanField(default=False)),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_edges', to='journeys.node')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_edges', to='journeys.node')),
            ],
            options={
                'db_table': 'edge',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('lines', models.ManyToManyField(db_table='stationline', related_name='station', to='journeys.line')),
            ],
            options={
                'db_table': 'station',
            },
        ),
        migrations.AddField(
            model_name='node',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journeys.station'),
        ),
        migrations.CreateModel(
            name='FastGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boarding_gate', models.CharField(max_length=50)),
                ('escalator', models.BooleanField(default=False)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journeys.line')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journeys.station')),
            ],
            options={
                'db_table': 'fast_gate',
            },
        ),
    ]
