# Generated by Django 5.2.6 on 2025-11-29 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('facility_id', models.IntegerField(primary_key=True, serialize=False)),
                ('facility_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'facility',
            },
        ),
        migrations.CreateModel(
            name='FacilityLoc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('detail_loc', models.TextField()),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journeys.facility')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journeys.line')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journeys.station')),
            ],
            options={
                'db_table': 'facility_loc',
            },
        ),
    ]
