# Generated by Django 5.2.6 on 2025-12-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0002_facility_facilityloc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fastgate',
            name='line',
        ),
        migrations.RemoveField(
            model_name='fastgate',
            name='station',
        ),
        migrations.AddField(
            model_name='fastgate',
            name='platform',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fastgate',
            name='transfer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fastgate',
            name='boarding_gate',
            field=models.CharField(default='', max_length=50),
        ),
    ]
