# Generated by Django 5.2.6 on 2025-12-04 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0003_remove_fastgate_line_remove_fastgate_station_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escalator',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('operation', models.BooleanField(default=True)),
                ('detail', models.CharField(blank=True, max_length=50, null=True)),
                ('edge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalator_detail', to='journeys.edge')),
            ],
            options={
                'db_table': 'escalator',
            },
        ),
    ]
